version: '3'
services:
  backend:
    build: ./api
    ports:
      - "4000:4000"
    links:
      - mongo
  frontend:
    build: ./client
    ports:
      - "80:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
